name: bg_custom_toast
description: "This package is used to show toast with multiple animation options."
version: 0.0.1
homepage: https://github.com/AbilashBG/bg_custom_toast.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
bg_custom_toast: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
